obj-m := kvm.o kvm-intel.o

kvm-objs := kvm_main.o ioapic.o coalesced_mmio.o kvm-ia64.o kvm_fw.o \
	irq_comm.o ../anon_inodes.o ../external-module-compat.o \
	../request-irq-compat.o

ifeq ($(CONFIG_IOMMU_API),y)
kvm-objs += iommu.o
endif

EXTRA_CFLAGS_vcpu.o += -mfixed-range=f2-f5,f12-f127
kvm-intel-objs := vmm.o vmm_ivt.o trampoline.o vcpu.o optvfault.o mmio.o \
               vtlb.o process.o memset.o memcpy.o kvm_lib.o
